spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/matgpt_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQLUSERNAME}
    password: ${MYSQLPASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLECLIENTID}
            client-secret: ${GOOGLECLIENTSECRET}
          kakao:
            client-id: ${KAKAOCLIENTID}
            client-secret: ${KAKAOCLIENTSECRET}



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false


    mail:
      host: smtp.gmail.com
      port: 587
      username: ${USERNAME}
      password: ${PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

    logging:
      level:
        root: INFO

    server:
      port: 8080

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWw


springdoc:
  enable-data-rest: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


chatgpt:
  api:
    key: ${GPTAPIKEY}



cloud:
  aws:
    s3:
      bucket: matgpt-dev
    credentials:
      access-key: ${AWSACCESSKEY}
      secret-key: ${AWSSECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

